Add service for stock endpoints
fulfillmenttools/fulfillmenttools-sdk-typescript pull request #38
Opened 2024-05-03 08:04 UTC by saschaheinl-fft

Currently our SDK does not provide a service for the `api/stocks` endpoint. This PR adds a service with methods for 

- CRUD stocks (GET, POST, PUT, DELETE)
- GET stock summaries
- GET stock distribution

2024-05-03 10:40 UTC, arnoerpenbeck commented
The new stock module must be exported in `fft-api/index.ts`

2024-05-03 11:01 UTC, nwilhelmFFT commented on src/fft-api/stock/fftStockService.ts
> +
Maybe we could introduce a shared function for building the query so we can reuse it in multiple places.

2024-05-03 11:13 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +      return this.apiClient.get<StockSummaries>(this.path, queryParams);
use correct path for stocks summaries

2024-05-03 11:13 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +      return this.apiClient.get<StockDistribution>(this.path);
use correct path for stocks distribution, include query params

2024-05-03 11:14 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['tenantArticleIds'] = query;
API param is called `tenantArticleId`

2024-05-03 11:15 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['locationRefs'] = locationRefs[0];
API param is called `locationRef`

2024-05-03 11:15 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['facilityServiceType'] = query;
`facilityServiceTypes`

2024-05-03 11:16 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['tenantArticleId'] = tenantArticleIds[0];
`tenantArticleIds`

2024-05-03 11:18 UTC, arnoerpenbeck requested changes
need to fix request path and param names

2024-05-03 14:19 UTC, nwilhelmFFT commented on src/fft-api/stock/fftStockService.ts
> +          let query = `${tenantArticleIds[0]}&tenantArticleIds=`;
Why do you not use buildQueryFromArray here?

2024-05-03 14:24 UTC, nwilhelmFFT commented on src/fft-api/stock/fftStockService.ts
> +  ): Promise<StockSummaries> {
Should we also include channelRefs ?

2024-05-06 09:04 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['tenantArticleIds'] = buildQueryFromArray('tenantArticleIds', tenantArticleIds, 500);
`tenantArticleId`

2024-05-06 09:13 UTC, saschaheinl-fft commented on src/fft-api/stock/fftStockService.ts
> +          queryParams['tenantArticleIds'] = buildQueryFromArray('tenantArticleIds', tenantArticleIds, 500);
Done

2024-05-06 09:23 UTC, nwilhelmFFT commented on src/fft-api/stock/fftStockService.ts
> +        tenantArticleIds = tenantArticleIds.slice(0, 499);
The slicing seems to already be done in `buildQueryFromArray`

2024-05-06 09:23 UTC, nwilhelmFFT commented on src/fft-api/stock/fftStockService.ts
> +          let query = `${locationRefs[0]}&locationRef=`;
You could also use `buildQueryFromArray` here

2024-05-24 14:11 UTC, arnoerpenbeck commented on src/common/httpClient/httpClient.ts
>        request.query(config.params);
fehlt hier nicht ein `else`?

2024-05-24 14:18 UTC, saschaheinl-fft commented on src/common/httpClient/httpClient.ts
>        request.query(config.params);
Nein, das `if` muss komplett weg. Pushe eben, danke für den Hinweis

2024-05-24 14:37 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +        queryParams['serviceTypes'] = serviceTypes;
`facilityServiceTypes`

2024-05-24 14:38 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +        queryParams['facilityRefs'] = facilityRef;
`facilityRef`

2024-05-24 14:38 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +        queryParams['tenantArticleIds'] = tenantArticleIds;
`tenantArticleId`

2024-05-24 14:38 UTC, arnoerpenbeck commented on src/fft-api/stock/fftStockService.ts
> +        queryParams['locationRefs'] = locationRefs;
`locationRef`

2024-05-24 14:39 UTC, arnoerpenbeck requested changes
some parameter names are still wrong

2024-05-27 06:07 UTC, arnoerpenbeck approved these changes

2024-05-27 06:19 UTC, nwilhelmFFT approved these changes

2024-05-27 06:38 UTC, merged